sudo: required
services:
 - docker

before_install:
 - docker build -t nithindindigala/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run nithindindigala/react-test npm test -- --coverage

after_success:
 - docker build -t nithindindigala/multi-client ./client
 - docker build -t nithindindigala/multi-nginx ./nginx
 - docker build -t nithindindigala/multi-server ./server
 - docker build -t nithindindigala/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 
 - docker push nithindindigala/multi-client
 - docker push nithindindigala/multi-server
 - docker push nithindindigala/multi-nginx
 - docker push nithindindigala/multi-worker

